FROM ruby:2.3-slim

ENV BUNDLER_VERSION=1.14.6
ENV GEM_VERSION=2.6.11

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs git \
  gem update --system $GEM_VERSION && \
  gem install bundler --version $BUNDLER_VERSION \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install --jobs 4 --retry 3

COPY . /app
