FROM ruby:2.3-slim

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs git
RUN mkdir /app

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY . /app
