version: '2.0'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  web:
    build:
      context: .
      dockerfile: "Dockerfile-dev"
    command: puma -C config/puma.rb -p 7000
    volumes:
      - .:/app
    ports:
      - "7000:7000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://docker:docker@db:5432/docker
